### ISSUE TITLE
Need better line colors

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#116]
Hello,
in the module quality graphs over time, e.g. here:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/fulltest.php
grades A, B, C have too similar colors, please update with something that can be more easily distinguished. 
Maybe swap with the blue and green from the other two curves.

Thanks,
Petra

**Comment by gneeser** [comment]
Petra,
I made some changes. How does it look now?

-Greg

**Comment by gneeser** [comment]
I made some changes. How does it look now?

Thanks,
Greg

**Comment by merkelp** [comment]
Hi Greg,
it looks good to me now. Thanks!

I noticed that on the same page, the legend in the 'Defects over time' 
plots should probably be changed from 'bad bumps' to 'bad pixels', since 
they include also dead pixels etc. This is just so when we show these 
plots at meetings or reviews we don't give the impression that we have a 
bump bonding problem.

Thanks,
Petra

**Comment by gneeser** [comment]
Good point, I updated the legend accordingly.
