### ISSUE TITLE
Require a comment to reject module

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#139]
Can we please require a comment whenever someone sets the next testing step to rejected?  This is not 100% essential if its tricky to implement, we could instead just berate the experts whenever they forget :)

**Comment by gneeser** [comment]
A comment is now required for a module to be set as Rejected. One thing to note though - if the notes field isn't filled, there won't be an error message; it just won't do anything.

**Comment by gneeser** [comment]
Another thing that I wanted to bring up, and I figure here is the best place: I thought it might be useful for us to bin rejected modules. So when rejecting a module, you would choose from a dropdown menu for why it was rejected. If I added this, then we could search by rejected bin, which would tell us, for example, how many modules we rejected because of dead pixels or unprogrammable ROCs versus bad IV. It may also give us more information than the Module Defects Over Time graphs.

My only qualm is that it would be a fair amount of work that may duplicate other functions in the database. This would be a more involved way to go about things, but if you all think it would be really useful I can give it a go. I can also give it a higher or lower priority than the new grading criteria.

**Comment by merkelp** [comment]
Hi Greg,

I think this can probably be achieved by other functionalities that are 
already there, since you have a lot of flags to select on the tested 
modules page.

If you really want to do it, I would suggest a lowish priority.

But, your previous comment reminded me of something. Right now, when you 
are modifying a module's status/next step by hand, you don't see what 
status it actually is in. I think it would be really useful to display a 
module's next testing step on its full test summary page, somewhre near 
the top.

Thanks,
Petra

**Comment by gneeser** [comment]
Petra,
The next testing step can currently be viewed in the block of text near the top of the page, whether you're in Full Test Summary or Full Test Submission.

-Greg

**Comment by merkelp** [comment]
Hi Greg,
yes, I saw. Probably overlooked it before, apologies.

Petra
