### ISSUE TITLE
New time stamp?

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#145]
Hello,

would it be possible to clone some of the quality monitoring plots and use a different time stamp on the x-axis? I am talking about the plots on the following pages:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/test_list.php
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/time.php
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/fulltest.php

For the new time stamp, would it be possible to grab the time of receiving a module at either Purdue or Nebraska, from RTI? This would be very close to the time the bare module was bump bonded, and it would be very useful to monitor as a function of that.
If it is possible, there would also be an additional plot that would be interesting: a histogram, where every bin on the x-axis is one week in this reception time, and the bin would be split into total number of modules, assembled, tested/graded at -20, A, B, C. All those components in different colors, so that one can easily see the amounts, and the grade yields evolving with time.

Thanks,
Petra

**Comment by gneeser** [comment]
Petra, 
I added received lines for the post-assembly and module quality graphs. The assembly over time graph already uses that field, however.

I'll set to working on that histogram as well.

-Greg

**Comment by merkelp** [comment]
Hi Greg, thanks, I saw. What I meant however, is to clone the plots (make a second set of them) and use this new time stamp on the x-axis instead of the assembly or testing time stamp.
Thanks,
Petra

**Comment by gneeser** [comment]
Petra,
Sorry about the delay, between spring break and other work concerns this took longer than anticipated. In any event, I have two plots ready for you to take a look at:
http://www.physics.purdue.edu/cmsfpix/Submission_t/graphing/assemblybybatch_grapher.php
http://www.physics.purdue.edu/cmsfpix/Submission_t/graphing/testbybatch_grapher.php

Is this what you were looking for?

I'm still working on the plots with the alternate x-axis, but they should be done soon.

-Greg

**Comment by merkelp** [comment]
Hi Greg,
Looks good, thanks!
Looking forward to the other plots.

Thanks,
Petra

**Comment by gneeser** [comment]
Petra,
How does this one look?
http://www.physics.purdue.edu/cmsfpix/Submission_t/graphing/postassemblybybatch_grapher.php

-Greg

**Comment by merkelp** [comment]
Hi Greg,
It's looking good. I am especially curious to see the plot with the different grades as a function of this time.

Thanks,
Petra

**Comment by gneeser** [comment]
Petra,
And here's the last one:
http://www.physics.purdue.edu/cmsfpix/Submission_t/graphing/testbybatch_lin_grapher.php

How does that look? Any bugs you can see with any of these?

-Greg

**Comment by lantone** [comment]
Hi Greg,

I'm loving this plot:

http://www.physics.purdue.edu/cmsfpix/Submission_t/graphing/testbybatch_grapher.php

Quick question: It's labeled as "Module -20 Grades".  There have been several modules that were manually graded as C based on the +17 results and never tested at -20.  How would you expect those modules to show up in this plot?  I think we'd want them to show as "Grade C" rather than "Received".  If that's not already the case could it be adjusted?  

Thanks, 

Jamie

**Comment by gneeser** [comment]
Jamie, 
I actually have a fix in there to account for that - if the module has been rejected, it is binned as "C." Should I change some text to reflect that?

**Comment by lantone** [comment]
Cool, thanks.  Since the grade is only assigned once, I think you could avoid any inaccuracies by just using "Module Grade" instead of "Module Grade at -20".

**Comment by lantone** [comment]
Oh, and does "Received" always correspond to a DB grade of "I"?  If so I'd suggesting changing "Received" to "Incomplete".  Or maybe there are some edge cases I'm not accounting for?

**Comment by gneeser** [comment]
Received corresponds to the timestamp (grouped by batch) when the modules are received at the assembly sites.

**Comment by lantone** [comment]
Sure, I get that, my point is that "Received" isn't a grade we give a module, so it sorta sticks out as odd in this plot.  If I were (naively) making this plot, I'd just get the module's grade from the DB and it'd always be A,B,C, or I.  But maybe there's a reason you don't do it that way?  Maybe a module isn't assigned a grade until it's assembled or something?

**Comment by gneeser** [comment]
Well, since I binned the batches by retrieving the received dates it made sense to me to use that as the baseline for how many were in a batch, and it more closely resembles the plots I based it off of. Now that you mention it, though, for this plot it does make a lot more sense to have that as "not graded" or something like that. So I'll do that!

**Comment by lantone** [comment]
ok great, thanks Greg!

**Comment by gneeser** [comment]
All,
I pushed the changes to the live version of the site. You can see the changes on the [Module Quality Graphs](http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/fulltest.php?) page.

Note that to get more details, you can click on the button up top to view more of the graphs. Due to increasing load times, I moved some of the less-used plots to a separate page.

-Greg
