### ISSUE TITLE
module not appearing in "tested modules" list

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#146]
Hi,

Module M-G-1-37:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-G-1-37

is not showing up in the Tested Modules List page:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/test_list.php?param19=m-g-1-37&param1=&param20=&param23=&param8=&param27=&param21=&param22=&comp2=%3D&param2=&comp3=%3D&param3=&comp4=%3D&param4=&comp10=%3D&param10=&comp11=%3D&param11=&comp5=%3D&param5=&comp7=%3D&param7=&comp12=%3D&param12=&comp13=%3D&param13=&param9=&comp25=%3D&param25=&comp18=&param18=

Any idea why?  The status is "Shipped", so in theory it should be visible there?

**Comment by gneeser** [comment]
The sensor name of the module was wrong in the database. Instead of reading "M_CR_106," the name was "MCR_106." There was a similar error for another module, M-G-2-09, which was MLL_106 instead of M_LL_106. I fixed both in the mysql, and I couldn't find any more misnamed modules like them. Until I can figure out why these modules were assigned the wrong sensor name I'll keep this issue open as a reminder.

**Comment by lantone** [comment]
Nice sleuthing, thanks :-)
