### ISSUE TITLE
KU:  Unable to Upload to Purdue DB using consolidated batch submit.

### ISSUE THREAD

**Issue by jking79** [puhep/pudb#157]
zip file trying to upload included.  Made with xRayupload.py in FPIXUtils.    https://github.com/fnal/FPIXUtils/files/162153/M-J-3-15.zip

**Comment by gneeser** [comment]
It seems that the method of sanitizing the name input was insufficient (it added newline characters). I'm using an alternate method that worked for this module. 

I mention this because it's possible it won't work for all cases. Even so, I tweaked the error output so that it will no longer say the data was successfully submitted in the case of this error.

If you see anything like this again, I'll take another look. 

-Greg
