### ISSUE TITLE
IV scan pass/fail requirements

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#25]
How exactly is the pass/fail decision made based on the IV scans?  For P-A-3-41, based on my math I(150)/I(100) is just barely greater than 2, but it is labeled as passing.

**Comment by khan62** [comment]
I think I found the issue. I've been assuming that the voltage values in IV scans were integers, so I search for the current values at the same indices as the values "100" and "150". Because you're using higher precision, those values don't exist, so it's trying to evaluate FALSE/FALSE > 2, which is throwing anomalous results. Can I assume that the given values will be within 0.5V of their target voltage? In that case I can use round() to find the 100V and 150V values.

**Comment by jstupak** [comment]
Yes I think it is safe to use round.  Thanks

**Comment by khan62** [comment]
The voltages are now rounded when evaluating the IV criteria. The I(150)/I(100) value for P-A-3-41 now reflects the proper pass/fail decision
