### ISSUE TITLE
Cannot proceed with an HDI

### ISSUE THREAD

**Issue by frmeier** [puhep/pudb#27]
HDI YHC69-1015-2-36 seems to be in asome weird state. We cannot promote it to attached to module. What to do? Checkboxes are inactive, no interaction possible.
http://www.physics.purdue.edu/cmsfpix/Submission_p/assembly/hdi.php?name=YHC69-1015-2-36

**Comment by khan62** [comment]
Promoting an HDI to Attached is done through the module assembly flow. When you have a module that is "Ready for HDI Assembly", in order to promote it to "HDI Attached" you must select an HDI from the dropdown menu, which is a list of all of the HDIs that are "Ready for Assembly". When you select an HDI in this way it automatically gets promoted in the HDI assembly flow. 

Also when you promote a module from "Ready for HDI Assembly" to "HDI Attached" the page will crash; just navigate away and back and it will be fine again. This is a bug I am currently in the middle of addressing.

If you have any more questions let me know.

**Comment by khan62** [comment]
The crashing problem should now be fixed too. Let me know if it gives you problems.
