### ISSUE TITLE
Better timestamps in DB

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#31]
Can we change the DB to use different timestamps?  Currently, things get timestamped based on when they are uploaded.  But we would prefer to have things timestamped based on when tests were performed.  We are already uploading the test time for the IV scans.  Can we also have a field to upload a time along with each test/scan/pic?

**Comment by khan62** [comment]
Now if you add a <TIME> tag within a <PIC> tag, if it is formatted properly, it will use that date/time instead of the current date/time.

Correct format: YYYY-MM-DD   OR   YYYY-MM-DD HH:MM:SS  (Note: hours are on 24-hour time)

Example master.xml:
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<PIC>
<NAME>BL_CR_923</NAME>
<FILE>testpic.jpg</FILE>
<TXT>testcomment.txt</TXT>
<TIME>1992-10-23 15:16:17</TIME>
<PART>module_p</PART>
</PIC>
</ROOT>

**Comment by khan62** [comment]
Would you prefer this tag be one level higher, so you can specify one time for a number of pictures?

**Comment by jstupak** [comment]
Sorry I missed this initially.  Yes, please move it up. Does this apply to TEST and SCAN fields as well?

**Comment by khan62** [comment]
TEST doesn't have a time associated to it, and SCAN uses the time from its own xml file, so they wouldn't be affected. This would just set every picture to the same time, the drawback of that being you couldn't specify different times for each picture.

**Comment by khan62** [comment]
<TIME> is now at the root level, so one timestamp will affect every picture. If you'd prefer it to affect pictures on an individual level again, just let me know and I can change it back.
