### ISSUE TITLE
consolidated batch submit error

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#37]
About half the time I try to upload a zip file, I get taken to a blank white page and nothing is actually added to the DB.  If I try the same zip again, it works after 1 or 2 more tries

**Comment by khan62** [comment]
Do you recall the URL of the blank white page?

**Comment by jstupak** [comment]
nope, sorry.  But if I see it again I will post it here

**Comment by jstupak** [comment]
http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/batchallsubmit_proc.php

**Comment by khan62** [comment]
I looked through the code, and I found a line that was requiring strict error reporting, and it's possible that was causing it to hang on what is supposed to be a non-displaying page. I'm not sure why it would only cause issues a fraction of the time, but I commented it out anyway.

**Comment by malhusse** [comment]
More on this issue:
- happened almost every time we tried to upload today
- it redirects to the blank white page 
- sometimes it will update the "Recently Updated" page with "Updated Fulltest Values", sometimes it won't
- The "Full Test Summary" page for the module gets updated with new plots from the "failed" submission

The cause of the issue is an HTTP 500 error. I took a screenshot of the network monitor and console developer tools in chrome:

batchallsubmit.php is successful and returns status code 200
batchallsubmit_proc.php is not and returns status code 500

<img width="1266" alt="screen shot 2015-07-30 at 8 11 28 pm" src="https://cloud.githubusercontent.com/assets/12919487/8998780/68a30430-36f7-11e5-8544-70d474a1dc06.png">

P.S.  Can you delete all the data added to P-A-2-07 on 07-30-15 except the first set?

**Comment by khan62** [comment]
Thanks for the detailed breakdown. Can you send me one of the zip files you're experiencing this with?

**Comment by khan62** [comment]
After talking to Mohammad, this seems like an issue again stemming from the fact that the page times out before it can fully process the large quantity of pictures in the zip files you are trying to upload. Is there a reason why you want these hundreds of graphs in a list instead of well-organized in MoReWeb?

**Comment by jstupak** [comment]
In short, yes.  This is what the bosses want, and we are not happy with MoReWeb.  It needs development, and we don't have extra manpower for this at FNAL right now.

I don't understand why timeout is an issue here, but I am admittedly ignorant.  The timeout does not occur when the zip is uploaded, I think.  If this was happening, the zip would be corrupted and we couldn't get anything out of it.  So the timeout is occurring while the XML is being parsed?  Why does this have to occur within some time window mandated by the Purdue IT folks?  Can't we just upload the zip, then have a cron job that runs every minute which checks for new zip files and processes them (completely decoupled from potential timeout issues)?

Thanks.

**Comment by khan62** [comment]
>So the timeout is occurring while the XML is being parsed? 
There are two places where a timeout could occur. The first is the time it takes for a file to be uploaded to the webserver, and the second is the time it takes the webserver to process the request. The problem we are encountering is the latter. Writing files to disk is an expensive operation, and there are a lot of files to be copied. 

>Why does this have to occur within some time window mandated by the Purdue IT folks?
Such a time window exists on every webserver, I just don't have control over it in this case.

>Can't we just upload the zip, then have a cron job that runs every minute which checks for new zip files and processes them (completely decoupled from potential timeout issues)?
This is possible. Another solution could be uploading multiple zip files that are capped at a certain size (say 10mb)

**Comment by jstupak** [comment]
we discussed this during the meeting, and would prefer to make the database upload more robust against timeout (the cron solution) rather than uploading multiple zips.  Is this a difficult change?  I would assume no, since this is already the way moreweb uploads work

**Comment by jstupak** [comment]
Just checking in.  Has there been any progress on this?  Thanks

**Comment by khan62** [comment]
This is my next priority. I found a way to run PHP scripts on the server as a background process (so they don't time out), so I'm going to try that. I want to try that before using a cron job, because cron will be slower to display your data.

**Comment by jstupak** [comment]
Sounds great.  Thanks a lot!

**Comment by khan62** [comment]
An update:
Something I need for running the PHP script as a background process might not be enabled on our servers. I emailed our Purdue IT guy about it, but in the (likely) event that we can't get it enabled, I'll have to switch to the cron implementation.

**Comment by khan62** [comment]
Our webservers are not able to run PHP as a command-line script. Unfortunately, as I should have realized earlier, this means neither of my ideas for a no timeout upload script would work. The only thing I can recommend now is to separate the zip file into multiple zips (maybe one for pictures, one for config files, one for data), each with its own master.xml file. I could also put a filesize cap on the form, so all the files in the zip can for sure be processed before the timeout. I'm sorry there isn't an easier solution. If you come up with an idea feel free to let me know.

**Comment by khan62** [comment]
Nick mentioned that someone asked in last Monday's meeting about why the method we use for MoReWeb couldn't work for the consolidated batch submit, so I'll elaborate on it here.

MoReWeb is a series of scripts written in Python. When you upload a file to be parsed with MoReWeb, it gets sent to a folder and waits. At the time designated by Cron (right now, every Sunday night/Monday morning), Cron will call the main file of MoReWeb, which trawls the folder with the uploaded files and runs them in the background. 

Consolidated batch submit is written in PHP, rather than Python. For this reason, it can't run in a comparable way because it can't be called to run on the command line by Cron. PHP can generally only be handled inside an HTML tag on a webpage. There is an option to make PHP runnable from the command line, but it is not currently implemented, and (as we have encountered numerous times in the past) it is hard to get ITaP to make modifications to the system.

I hope that's a thorough explanation of the issue, but if you have any more questions feel free to ask.

**Comment by jstupak** [comment]
were any changes to the DB made?

**Comment by jstupak** [comment]
I just tried uploading a slimmed-down zip file 18 times.  16 times the upload was successful.  One time it failed after processing just 43 images.  So if we want this to work reliably, we should stick to ~20 plots per zip file.  We want to upload 141 plots, so we would have to upload ~7 zip files to get the images in the DB, and who knows how many to get the 70 configs in the DB.  Not really a practical option.

The best option I see at this point is to create an easy way for shifters to request that a set of test results for a given module be wiped clean.  It is clear to the shifters when an upload fails, so they could just request to have the partial test results removed, and try again to upload.  This avoids having partial duplicate entries in the DB.  I know Kamal didnt want to give us permission to delete things ourselves, but maybe just a button which would allow for someone at Purdue to do the delete would be okay?  It would be nice if the shifter could immediately upload new results, instead of waiting for the cleanup to happen, so the request should include a time or something so it is clear what should be deleted (only test results uploaded within a ~10 minute window prior to the time specified in the request).  This feature would also be useful in case a shifter uploads results but we later realize there was an issue with the HV or something and want to remove the junk results.
