### ISSUE TITLE
HDI Naming/Promotion Issue

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#58]
Alex found an issue with the DB when promoting stress-test parts. Here's his description:

"When you submit an HDI individually you have the choice of YHC69 1015-panel number- location or YHD19 1018-panel number- location and when these HDI are assembled onto modules they recieve names like P-A-panel number-location or P-B-panel-location. When you submit a batch of HDI however the HDI recieve names such as 1018-1015-panel-location. when these HDI are attached the modules name are P-panel-location, no A or B."

**Comment by khan62** [comment]
This is because of how the database names new modules. It adds the A, B, etc if the batch/date code matches a certain string. The stress-test HDIs did not have the proper batch/date codes, so the "X-" strings were never appended to the new module name. This will not happen when we have real HDIs unless their batch/date codes are entered incorrectly.
