### ISSUE TITLE
Naming Conventions for Production

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#60]
When we start production, the naming convention calls for switching from P- module names to M- during production. Preproduction wafers are from 900-999. Production wafers will range from 000-299. When a module is promoted to assembled the database should construct the name based on the HDI batch/panel/position and also if the module is from a production or preproduction wafer.

Also, please double-check that adding a new batch of work order/date code for HDI increments the naming in letters. That is, batch 5 of HDI (work order/date code currently unknown) corresponds to E in the name, batch 6 corresponds to F, etc...

**Comment by khan62** [comment]
I just checked my code, and the database does already discriminate between production and preproduction when generating the new module name.

**Comment by khan62** [comment]
The code before was set up so that you'd have to add a new line every time a new work order was added. Now I've changed it so it dynamically checks the database and the letter code is assigned based on the order the work orders were added. It only goes up to "Z", so if we have more than 26 batches we might have to venture into the Greek alphabet
