### ISSUE TITLE
Sorting 'On Module' HDI Does Not Work

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#64]
When I try to sort HDI in the 'on module' bin the displayed data doesn't change. I tried sorting by what module is attached, the modified date, and assembly location.

**Comment by khan62** [comment]
The problem was a quirk with the PHP function array_multisort, which sorts multi-dimensional arrays. You have to include as parameters every array that is to be sorted, or else it goes haywire. I recently added a new column to a 2-dimensional array that was being sorted, but I didn't include it into some of the existing array_multisort functions, so they acted improperly.

The problem is now fixed.
