### ISSUE TITLE
Summary IV plots

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#82]
Hi, it would be very nice if we could add one plot on this page: 
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/pos.php
that shows all the IVs for all the different sensor positions lumped together.

Also: can we make sure to always use the final Fermilab measurement if it is available, not the ones from the assembly sites?

Thanks,
Petra

**Comment by NickHinton** [comment]
We originally chose not to include such a plot because we thought it would be so cluttered as to be unusable. But we can add one and see how it looks. 

As for your second point, the idea of these plots was to keep an eye on the wafer position-dependent increase in leakage current of a module, which has happened after assembly. I'm worried that if we instead plot the IV at Fermilab, any modules that have their IV increased post-assembly could end up confusing those statistics. Hopefully this is a non-issue for production modules, but we'll see...

Do you think we have a need for both sets of IV measurements?

Thanks,
Nick

**Comment by merkelp** [comment]
hmm, maybe the combined plot (all positions) could use the Fnal 
measurements, and the split ones just stay as they are?

**Comment by khan62** [comment]
The top graph on this page is a graph of all Fermilab IV scans. (The fraction on the side is wrong; that is an issue I need to address)
http://www.physics.purdue.edu/cmsfpix/Submission_t/summary/pos.php

**Comment by khan62** [comment]
The fraction has now been fixed as well.

**Comment by gneeser** [comment]
We've modified the plots for additional readability:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/pos.php? 

If there are any additional changes to be made, aesthetic or otherwise, just let me know. Otherwise, I believe we can close the issue.

**Comment by merkelp** [comment]
This looks very nice, thanks!

Petra

**Comment by gneeser** [comment]
My pleasure.
